name: Test Prefect test installation

on:
  push:
    paths:
      - .github/workflows/prefect-installation-macos.yml
    branches:
      - main
      - prefect-install-test

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.9]
    name: ${{ matrix.os }} test installation
    steps:
      - name: Checking out git repo & Prefect submodule
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup conda
        uses: s-weigand/setup-conda@v1

      - name: Update conda
        run: conda update -n base -c defaults conda

      - name: downloading pip 
        run: conda install pip

      - name: (Linux/MacOS) pip downloading prefect dev directory
        if: ${{ matrix.os != 'windows-latest' }}
        run: pip install -e ./prefect/ --user

      - name: (Windows) pip downloading prefect dev directory 
        if: ${{ matrix.os == 'windows-latest' }}
        run: python -m pip install -e ./prefect/ --user

      - name: Install dependencies & test Prefect dev installation
        run: conda env create -f conda-environment.yaml -n prefect-test

      - name: Test with pytest on main branch (ignoring Prefect dev directory)
        run: |
          conda install pytest
          pytest --ignore=./prefect

