name: Prefect Installation on Windows

on:
  push:
    paths:
      - .github/workflows/prefect-installation-windows.yml
    branches:
      - main
      - prefect-install-test

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        
        #os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [windows-latest]
        python-version: [3.9]
    name: Python ${{ matrix.os }} example
    steps:
      - name: Checking out git repo & Prefect submodule
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup conda
        uses: s-weigand/setup-conda@v1

      - name: Checking Conda Version
        run: conda --version

      - name: Checking Python Version
        run: which python

      - name: List dependencies
        run: conda list

      - name: Update conda
        run: conda update -n base -c defaults conda

      - name: Install Prefect
        run: pip install prefect

      - name: Install dependencies & test Prefect dev installation
        run: conda env update --file conda-environment.yaml --name base
      
      - name: Test with pytest on main branch (ignoring Prefect dev directory)
        run: |
          conda install pytest
          pytest --ignore=./prefect