name: Prefect Installation using Conda

on:
  push:
    branches:
      - prefect-install-test

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v3
          submodules: true

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Update conda
      run: |
        conda update -n base -c defaults conda

    - name: List dependencies
      run: |
        conda list

    - name: Install dependencies
    # conda env update --file environment.yml --name base
      run: |
        $CONDA/bin/conda env update --file conda-environment.yaml --name base
      
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
