name: Prefect Installation

on:
  push:
    branches:
      - prefect-install-test

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Update conda
      run: |
        conda update -n base -c defaults conda

    - name: List dependencies
      run: |
        conda list

    - name: Install dependencies
      run: |
        $CONDA/bin/conda env update --file conda-environment.yaml --name base
      
    - name: Test with pytest
      run: |
        conda install pytest
        $CONDA/bin/pytest --ignore=./prefect
